name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Build cyb
        run: yarn build
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"
          CHAIN_ID: "bostrom"

      - name: Server-side render
        uses: brycedorn/react-snap-action@v1.0.2
        with:
          root: .
          output: ./build

      - name: Deploy 🚀
        uses: aquiladev/ipfs-action@master
        with:
          path: ./build
          service: infura
          infuraProjectId: ${{ secrets.INFURA_PROJECT_ID }}
          infuraProjectSecret: ${{ secrets.INFURA_PROJECT_SECRET }}
