name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

      - name: Build cyb
        run: yarn build
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"
          CHAIN_ID: "bostrom"

      # - name: Server-side render
      #   uses: brycedorn/react-snap-action@v1.0.2
      # with:
      #   root: .
      #   output: ./build

      - name: Deploy 🚀
        # uses: aquiladev/ipfs-action@master
        # with:
        #   path: ./build
        #   service: infura
        #   infuraProjectId: ${{ secrets.INFURA_PROJECT_ID }}
        #   infuraProjectSecret: ${{ secrets.INFURA_PROJECT_SECRET }}
        id: ipfs
        uses: dasein108/ipfs-github-action@master
        with:
          path_to_add: ./build
          cluster_host: ${{ secrets.IPFS_CLUSTER }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: show urls
        run: echo /ipfs/${{ steps.ipfs.outputs.cid }}
      - name: Dynamic Badges
        uses: Schneegans/dynamic-badges-action@v1.6.0
          with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 8f5ee5779ab1668d042bfad9f65b4c0f
          filename: deploy.json
          label: IPFS
          message: ${{ steps.ipfs.outputs.cid }}
          color: orange
