name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: test
        id: test
        uses: actions/hello-world-docker-action@main
        with:
          who-to-greet: "Mona the Octocat"

      - name: show test pipeline
        run: echo time:${{ steps.test.outputs.time }}
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Build cyb
        run: yarn build
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"
          CHAIN_ID: "bostrom"

      # - name: Server-side render
      #   uses: brycedorn/react-snap-action@v1.0.2
      # with:
      #   root: .
      #   output: ./build

      - name: Deploy 🚀
        # uses: aquiladev/ipfs-action@master
        # with:
        #   path: ./build
        #   service: infura
        #   infuraProjectId: ${{ secrets.INFURA_PROJECT_ID }}
        #   infuraProjectSecret: ${{ secrets.INFURA_PROJECT_SECRET }}
        id: ipfs
        uses: dasein108/ipfs-github-action@master
        with:
          path_to_add: ./build
          cluster_host: ${{ secrets.IPFS_CLUSTER }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: show urls
        run: echo /ipfs/${{ steps.ipfs.outputs.cid }}
        run: echo ${{ steps.ipfs.outputs.url }}
