name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

      - name: Build cyb
        run: yarn build
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"
          CHAIN_ID: "bostrom"

      # - name: Server-side render
      #   uses: brycedorn/react-snap-action@v1.0.2
      # with:
      #   root: .
      #   output: ./build

      - name: Deploy to IPFS 🚀
        # uses: aquiladev/ipfs-action@master
        # with:
        #   path: ./build
        #   service: infura
        #   infuraProjectId: ${{ secrets.INFURA_PROJECT_ID }}
        #   infuraProjectSecret: ${{ secrets.INFURA_PROJECT_SECRET }}
        id: ipfs
        uses: dasein108/ipfs-github-action@master
        with:
          path_to_add: ./build
          cluster_host: ${{ secrets.IPFS_CLUSTER_HOST }}
          ipfs_gateway: { { vars.INPUT_IPFS_GATEWAY } }
      - name: show urls
        run: echo /ipfs/${{ steps.ipfs.outputs.cid }}

      - name: send build result to telegram
        env:
          CLEAN_MVN_REPO: ${{ secrets.TELEGRAM_TOKEN }}
        if: env.TELEGRAM_TOKEN != null
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}

            Repository: ${{ github.repository }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}

            IPFS URL: ${{ steps.ipfs.outputs.url }}
